image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
    - npm install --silent

stages:
    - test
    - build

job 1:
  stage: test
  script: 
    - node_modules/.bin/ng test
  tags:
    - front-end
    
job 2:
  stage: test
  script: 
    - node_modules/.bin/ng e2e
  tags:
    - front-end

release_job:
  stage: build
  script: node_modules/.bin/ng build --prod -aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  tags:
    - front-end

