image: node:alpine

stages:
    - build
    - test

test:
  stage: test
  before_script:
    - npm install --silent
  script: 
    - npm run test
    - npm run e2e
  tags:
    - front-end

build:
  stage: build
  script: npm build
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  tags:
    - front-end

